export enum PostActionType {
  POSTS_LOADED_SUCCESS = "POSTS_LOADED_SUCCESS",
  POSTS_LOADED_FAIL = "POSTS_LOADED_FAIL",
  ADD_POST = "ADD_POST",
  DELETE_POST = "DELETE_POST",
  UPDATE_POST = "UPDATE_POST",
  FIND_POST = "FIND_POST"
}